#!/bin/bash
# echo "require(rmarkdown); render('$1.Rmd', output_file='$1.tex')" | R --vanilla &&
pandoc -s -f markdown "$1.Rmd" -o "$1.tex" > /dev/null &&
#sed "s#begin{document}#begin{document}\n\\\includepdf\[pages=1,fitpaper\]{../pdfs/cover-$1.pdf}\n#" "$1.tex" | grep -A4 "begin{document}"
 sed "s#\\\frontmatter#\\\frontmatter\n\\\includepdf\[pages=1,fitpaper\]{../pdfs/cover-$1.pdf}#" "$1.tex" > tmp &&
 mv tmp "$1.tex" &&
 sed "s#pgfplots}#pgfplots}\n\\\usetikzlibrary{positioning,arrows.meta}#" "$1.tex" > tmp &&
 mv tmp "$1.tex" &&
 sed "s#\\\usepackage{xcolor}#\\\usepackage\[table\]{xcolor}\n#" "$1.tex" > tmp &&
 mv tmp "$1.tex" && 
 echo "require(tinytex); pdflatex('$1.tex')" | R --vanilla &&
 #pdflatex "$1.tex" > /dev/null &&
 #find . -maxdepth 1 -name "*.pdf" -exec mv {} ../pdfs \;
 ls | grep -P "$1\.(?!(Rmd|tex|pdf))" | xargs -I _ rm _ &&
 ls | grep *.pdf | xargs -I _ mv _ ../pdfs/_ &&
 echo "Done!"



